/* Transform-driven belt: independent of native scroll rounding and touch focus. */
(()=>{'use strict';
function init(){const dock=document.querySelector('.platform-dock');if(!dock||dock.dataset.beltReady)return;const originals=[...dock.querySelectorAll(':scope > a')];if(!originals.length)return;dock.dataset.beltReady='true';
const track=document.createElement('div'),group=document.createElement('div');track.className='apps-belt';group.className='apps-belt-group';originals.forEach(a=>group.append(a));track.append(group);const copy=group.cloneNode(true);copy.setAttribute('aria-hidden','true');copy.classList.add('apps-belt-copy');copy.querySelectorAll('a').forEach(a=>a.tabIndex=-1);track.append(copy);dock.append(track);dock.classList.add('belt-ready');
const reduced=matchMedia('(prefers-reduced-motion:reduce)');let touching=false,hover=false,visible=true,timer;
function sync(){const disabled=reduced.matches||document.documentElement.classList.contains('motion-paused');dock.classList.toggle('belt-static',disabled);track.style.setProperty('animation-play-state',(disabled||touching||hover||!visible||document.hidden||dock.querySelector(':focus-visible'))?'paused':'running','important')}
dock.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hover=true;sync()}});dock.addEventListener('pointerleave',()=>{hover=false;sync()});dock.addEventListener('pointerdown',()=>{touching=true;clearTimeout(timer);sync()});function release(){if(!touching)return;timer=setTimeout(()=>{touching=false;sync()},900)}addEventListener('pointerup',release);addEventListener('pointercancel',release);dock.addEventListener('focusin',sync);dock.addEventListener('focusout',()=>setTimeout(sync,0));document.addEventListener('visibilitychange',sync);new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['class']});reduced.addEventListener('change',sync);if('IntersectionObserver' in window)new IntersectionObserver(e=>{visible=e[0].isIntersecting;sync()}).observe(dock);sync();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
